### ISSUE TITLE
Throwing of Unserializable Issue Should Serialize to Undefined

### ISSUE THREAD

**Issue by amydevs** [MatrixAI/js-rpc#36]
### Specification

In the case where a handler throws an unserializable error (bigint, symbol, etc.), the server should return a ErrorRPCRemote error to the client with the cause being `undefined`. The server should also dispatch an event to tell the user that a recoverable error has happened, and that one of their handlers is possibly erroneous.

### Additional context

#34 

### Tasks

1. ...
2. ...
3. ...

**Comment by CMCDragonkai** [comment]
Was solved here: https://github.com/MatrixAI/js-rpc/commit/b98a3b07361eff0636571e03e2aa1cf1041f1e22
