### ISSUE TITLE
Make `rpc` handlers abstract arrow function properties.

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-rpc#5]
### Specification

Currently the `rpc` handlers are abstract methods that need to be implemented. These should be an abstract arrow function property and handlers should be implemented as arrow functions. This will allow us to use them without rebinding the `this` context.

This should be done during the agent migration PR.

### Additional context

* Should be done during MatrixAI/Polykey#512 
* Related MatrixAI/Polykey#509 .

### Tasks

1. Update the abstract handler's `handle` methods to be abstract arrow function properties.

**Comment by CMCDragonkai** [comment]
This is moved here as updating this in js-rpc will force the adoption of it in Polykey when it updates.

**Comment by addievo** [comment]
Resolved in https://github.com/MatrixAI/js-rpc/pull/8

**Comment by tegefaulkes** [comment]
You need to re-open this. It should be closed automatically by #8 being merged.

**Comment by CMCDragonkai** [comment]
@addievo this issue is not fixed in your PR #8. You need to change the classes to specify that handlers should a be an arrow property and add tests into the RPC to be make it to be the case.

I'm not sure if class methods even satisfy arrow property types, and vice versa.
